### ISSUE TITLE
Schema extracting does not complete when input and result use the same type that has nested data types

### ISSUE THREAD

**Issue by oofp** [morpheusgraphql/morpheus-graphql#543] opened 2020-10-07 17:00 UTC
Here as an example:
```
data UserType = UserManager | UserTechLead | UserDev | UserQA deriving (Generic, GQLType)
data UserName = UserName 
  { firstName :: Text
  , lastName :: Text
  } deriving (Generic, GQLType)
data User = User
  { userName :: UserName
  , userType :: UserType
  , userDsc :: Text
  } deriving (Generic, GQLType)   
data Query m = Query
  { user :: User -> m User
  } deriving (Generic, GQLType)
resolveUserQ :: User -> ResolverQ e IO User
resolveUserQ usr = return usr  
```
UserName is nested inside User. It compiles successfully but schema retrieval stuck

**Comment by kamek-pf** [comment] 2020-10-28 20:55
I think Morpheus is currently lacking support for nested input types.
I can reproduce this just by having nested input types, regardless of what the return type is.

**Comment by oco-adam** [comment] 2020-11-10 08:21
I can also reproduce this just by having nested input object types. Is there a suggested workaround for this other than flattening everything to remove nesting?

**Comment by kamek-pf** [comment] 2020-11-10 15:57
I found solution. 
If you need to use a record as a nested input, instead of deriving `GQLType`, you can write the instance manually and set the proper kind:
 ```haskell
data MainThing = MainThing
    { input :: NestedThing
    }
    deriving (Generic, Show, GQLType)

-- Nested fields, requires manually deriving GQLType to set the INPUT kind
data NestedThing = NestedThing
    { field1 :: Text
    , field2 :: Text
    }
    deriving (Generic, Show)

instance GQLType NestedThing where
    type KIND NestedThing = INPUT
    description _ = Just "Nested thing docs"
```

Maybe we could send a PR to update the docs and make this more obvious ?

**Comment by oco-adam** [comment] 2020-11-11 13:04
@kamek-pf  I can confirm that your solution worked for me - thank you! :) 

I'm a Haskell beginner and it definitely would have helped me if this was included in the docs, so I think a PR to update the docs would be a good idea.

**Comment by nalchevanidze** [comment] 2020-11-25 22:19
@kamek-pf @oco-adam   it is not nesting, problem is that you use Output Type as Input Type. that is not allowed in GraphQL.

currently the library does not report an error message about this violation, which will be fixed in the future

**Comment by nalchevanidze** [comment] 2020-11-27 20:41
now you can fix it with  `GQLTypeOptions` supports new option `prefixInputType`.

it will fix your problem, if you derive them with it (like in this example)

```hs
data UserType = UserManager | UserTechLead | UserDev | UserQA deriving (Generic, GQLType)

data UserName = UserName 
  { firstName :: Text
  , lastName :: Text
  } deriving (Generic)

instance GQLType UserName where
    typeOptions _ opt = opt {prefixInputType = True}

data User = User
  { userName :: UserName
  , userType :: UserType
  , userDsc :: Text
  } deriving (Generic, GQLType)   

data Query m = Query
  { user :: User -> m User
  } deriving (Generic, GQLType)


resolveUserQ :: User -> ResolverQ e IO User
resolveUserQ usr = return usr  
```

so will graphql generate following schema.

```gql
enum UserType {
  UserManager 
  UserTechLead 
  UserDev 
  UserQA
} 

input InputUserName { 
  firstName : String!
  lastName : String!
} 

type UserName { 
  firstName : String!
  lastName : String!
} 

type User { 
  userName : UserName!
  userType : UserType!
  userDsc : String!
}   

type Query {
  user ( 
    userName : InputUserName!
    userType : UserType!
    userDsc : String!
  ): User
} 
```

notice: 
  1. argument `userName`uses input type  `InputUserName`
  2. we don't have to generate input type for type `User` since its fields are represented as arguments 

otherwise you will get error message :

```json
{
  "errors": [
    {
      "message": "It appears that the Haskell type \"UserName\" was used as both input and output type, which is not allowed by GraphQL specifications.\n\n If you enable \"{ prefixInputType = True }\" in \"GQLType.typeOptions\", the compiler can generate a new input type \"InputUserName\" to solve this problem.",
      "locations": []
    }
  ]
}
```

**Closed** 2020-11-27 21:12 UTC
Labels: GraphQL Server, bug
